class SYNTAX:
    DEFINE_PROPERTY = "-"
    DEFINE_WINDOW_PROPERTY = "-$"
    DEFINE_FILE_PATH = "%="
    DEFINE_EOL = ":"
    DEFINE_COMMENT_LINE = "!#"
    DEFINE_NEW_BLOCK_START = "{"
    DEFINE_NEW_BLOCK_END = "}"
    DEFINE_PROPERTY_START = "["
    DEFINE_PROPERTY_END = "]"
    DEFINE_PROPERTY_LIST_START = "("
    DEFINE_PROPERTY_LIST_END = ")"
class OPERATORS:
    SET_VALUE = "="
    ADD_VALUE = "+="
    SUB_VALUE = "-="
    MUL_VALUE = "*="
    DIV_VALUE = "/="
    MOD_VALUE = "%="
    INCREMENT = "++"
    DECREMENT = "--"
    EQUAL = "=="
    NOT_EQUAL = "!="
    GREATER_THAN = ">"
    LESS_THAN = "<"
    GREATER_THAN_OR_EQUAL = ">="
    LESS_THAN_OR_EQUAL = "<="
    AND = "&&"
    OR = "||"
class BLOCK_TYPE:
    CONTENT_BLOCK = "container"
    
class MESSUREMENTS:
    PIXELS = "px"
    PERCENT = "%"
    VW = "vw"
    VH = "vh"
