import lib.getWindowProperty as getWindowProperty
import GRAMMAR as GRAMMAR
def getListOfLines(data):
    return data.split("\n")
def getLengthOfList(data):
    return len(data)

def lexer(lines):
    ret_data = """
    <!--
        This was generated by the Bagel Language 
        This is a simple language that is used to create an advanced, stylistic, and reactive web pages.
    -->"""
    wp=getWindowProperty.getWindowPropertyLexer(lines, GRAMMAR.SYNTAX.DEFINE_WINDOW_PROPERTY)
    wpLength=getLengthOfList(wp)
    cIfWp = 0
    for type in wp[0]:
            x = getWindowProperty.returnWindowPropertyAsHtml(type, wp[1][cIfWp])
            print(x)
            cIfWp += 1
            
            
